### PR TITLE
update to make it compatible for phpbb forum posts

### PR DESCRIPTION
**Pull request by kremsy**
@see https://github.com/golonka/BBCodeParser/issues/20

### CODE REVIEW

**Comment by golonka** [comment]
I don´t see any downside to this. If you make the test pass I could merge it.

**Comment by kremsy** [comment]
cant see what exactly went wrong on the error checks

**Comment by golonka** [comment]
Seems like the link and linebreak tags fails.

More info in the log
https://travis-ci.org/golonka/BBCodeParser/jobs/78100600

**Comment by kremsy** [comment]
Alright, know the cause for the link issue, but didnt found out about the linebreak one yet.

**Pull request closed without merging**
