### PR TITLE
New internal parser and processor

### PR DESCRIPTION
**Pull request by thunderer**
Hi, as per my comment in #25 I rewrote internals of your main library class using Shortcode library. Summary of changes:

* added dependency on `thunderer/shortcode` package,
* changed array of regexes to the fully configured Processor object,
* using RegularParser implementing proper nesting detection in any case,
* handling case insensivity by searching for lowercased handler name,
* quoted parameter names in tests where necessary,
* shortcodes can be now only referenced by their names, they do not have aliases,
* removed composer.lock and added it to .gitignore as it's auto-generated.

All tests pass. I'm open to discussion as I'd really like my code to serve as a backbone for solution like yours. If you have any question or want me to change something, just ask! :)

### CODE REVIEW

**Comment by golonka** [comment]
Looks really good. Will play around with it tomorrow.
Feels like it makes everything more flexible and a better base to work from.

**Comment by thunderer** [comment]
@golonka did you review this PR? Is it good for you?

**Comment by golonka** [comment]
Sorry for not writing back to you.
It looks good!
My only concerns are that it still parses bbcode inside code tags. Also that it breaks backward compability, so the pr should be targeted for the develop branch.

Thanks for your work with the package.

**Comment by thunderer** [comment]
@golonka could you provide failing test cases for me (separate branch, link to gist or even PR to my fork?) so that I could resolve all the issues? I just need to know what's missing.

**Comment by golonka** [comment]
https://gist.github.com/golonka/7592919fefccd153334c
Added the test case that is in test.php.
The error that is thrown by phpunit is in test.txt and in output.txt is what is sent to the browser.

**Comment by thunderer** [comment]
I fixed the issues and opened another PR to `develop`, please check out #29.

**Pull request closed without merging**
